import {
  Search,
  Share2,
  Target,
  FileText,
  Code,
  Mail,
  BarChart3,
  TrendingUp,
  Lightbulb,
  Users,
  Shield,
} from "lucide-react";
import type { Service } from "@/lib/types/services";

export const SERVICES_DATA: Service[] = [
  {
    id: "seo",
    title: "Search Engine Optimization (SEO)",
    description: "Get your business found by the right customers.",
    icon: Search,
    category: "Digital Marketing",
  },
  {
    id: "social-media",
    title: "Social Media Marketing",
    description: "Transform your social presence into a sales engine.",
    icon: Share2,
    category: "Social Media",
  },
  {
    id: "ppc",
    title: "Paid Advertising (PPC)",
    description: "Achieve instant results and maximize your ad spend.",
    icon: Target,
    category: "Advertising",
  },
  {
    id: "content-marketing",
    title: "Content Marketing",
    description: "Tell your story, attract your audience.",
    icon: FileText,
    category: "Content",
  },
  {
    id: "web-design",
    title: "Web Design & Development",
    description: "Build your dream online presence.",
    icon: Code,
    category: "Development",
  },
  {
    id: "email-marketing",
    title: "Email Marketing",
    description: "Nurture leads and drive loyal customer relationships.",
    icon: Mail,
    category: "Email",
  },
  {
    id: "analytics",
    title: "Analytics and Reporting",
    description: "Understand your performance, optimize your strategy.",
    icon: BarChart3,
    category: "Analytics",
  },
  {
    id: "cro",
    title: "Conversion Rate Optimization (CRO)",
    description: "Turn more visitors into valuable customers.",
    icon: TrendingUp,
    category: "Optimization",
  },
  {
    id: "strategy",
    title: "Digital Marketing Strategy",
    description: "Develop a clear roadmap for online success.",
    icon: Lightbulb,
    category: "Strategy",
  },
  {
    id: "influencer",
    title: "Influencer Marketing",
    description: "Amplify your brand's reach through authentic voices.",
    icon: Users,
    category: "Influencer",
  },
  {
    id: "pr",
    title: "Public Relations (PR) & Online Reputation Management",
    description: "Build trust and protect your brand's image.",
    icon: Shield,
    category: "Public Relations",
  },
];
